---
permalink: /:year/:month/:day/:title/index.html
maruku:
  png_dir: images/latex
  png_url: /images/latex
  use_tex: false
  use_divs: false
lsi: false
destination: ./_site
markdown: maruku
pretty_style: html_extension
pygments: true
auto: true
server_port: 4000